FROM registry.cn-hangzhou.aliyuncs.com/masa/dotnet_sdk:6.0.100-preview.7-nodejs14.16.1-wasm-tools  AS base
WORKDIR /app
COPY . .
RUN dotnet publish "./src/Doc/MASA.Blaozr.Doc.WebAssembly.Host/MASA.Blazor.Doc.WebAssembly.Host.csproj" -c Release -o /app/publish

FROM caddy:alpine
WORKDIR /app
COPY --from=base /app/publish/wwwroot /usr/share/caddy/
