name: Bug Report
description: Create a report about something that is not working
title: "[Bug Report] "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    attributes:
      label: Masa.Blazor version
    validations:
      required: true
  - type: dropdown
    id: hosting-model
    attributes:
      label: Hosting model
      options:
        - Blazor Server
        - Blazor WebAssembly
        - Static Server
        - Interactive Server
        - Interactive WebAssembly
        - Interactive Auto
        - Blazor Hybird(MAUI/WPF/WinForm)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: |
        We will close this issue if:
        - The repro project you share with us is complex. We can't investigate custom projects, so don't point us to such, please.
        - If we will not be able to repro the behavior you're reporting.
        - If the repro project is attached as a `.zip` file.
        - If the GitHub repro project is set to `Private`.
  - type: textarea
    attributes:
      label: Reproduction code
      description: |
        Reproduction code works fine in [Playground](https://github.com/masastack/MASA.Blazor/blob/main/src/Masa.Blazor.Playground/Pages/Index.razor)
      render: razor
  - type: input
    attributes:
      label: .NET version
      description: |
        Run `dotnet --version`
