name: Bug Report
description: Create a report about something that is not working
title: "[Bug Report]: "
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: |
        We will close this issue if:
        - The repro project you share with us is complex. We can't investigate custom projects, so don't point us to such, please.
        - If we will not be able to repro the behavior you're reporting.
        - If the repro project is attached as a `.zip` file.
        - If the GitHub repro project is set to `Private`.
    validations:
      required: false
  - type: input
    attributes:
      label: Reproduction code
    validations:
      required: false
  - type: input
    attributes:
      label: Masa.Blazor version
    validations:
      required: true
  - type: input
    attributes:
      label: Blazor version
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

