name: Azure Static Web Apps CI/CD v1

on:
  push:
    branches:
      - main
    paths:
      - src/BlazorComponent/src/Component/**
      - src/Masa.Blazor/**
      - docs/**
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - src/BlazorComponent/src/Component/**
      - src/Masa.Blazor/**
      - docs/**

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: git submodule foreach git checkout main
      - name: setting dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - name: setting tools
        run: dotnet workload install wasm-tools
      - name: Copy Static Resources
        id: copyStaticResources
        run: |
          dotnet build Masa.Blazor.Docs.sln
          dotnet publish docs/Masa.Docs.WebAssembly/Masa.Docs.WebAssembly.csproj -c Release -o publish
          cp -rf docs/Masa.Docs.WebAssembly/staticwebapp.config.json publish/wwwroot
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_PLANT_0C2439C10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "publish/wwwroot" # App source code path (because skip, so same to output_location)
          skip_app_build: true
          skip_api_build: true
          production_branch: "main"
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_PLANT_0C2439C10 }}
          action: "close"
