name: create doc index
# create doc index,send to ALGOLIA
# auto create when doc changed
on:
  push:
    branches:
      - main
    paths:
      - docs/MASA.Docs/src/Masa.Framework.Docs/wwwroot/pages/**/zh-CN.md
      - docs/MASA.Docs/src/Masa.Framework.Docs/wwwroot/pages/**/en-US.md
      - docs/MASA.Docs/src/Masa.Stack.Docs/wwwroot/pages/**/zh-CN.md
      - docs/MASA.Docs/src/Masa.Stack.Docs/wwwroot/pages/**/en-US.md
      - docs/Masa.Blazor.Docs/wwwroot/pages/**/en-US.md
      - docs/Masa.Blazor.Docs/wwwroot/pages/**/zh-CN.md
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: git pull
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - run: git submodule foreach git checkout main
    - name: setting dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          7.0.x
    - name: run index-create tools
      env:
        MASA_DOMAIN: "https://docs.masastack.com"
        MASA_ALGOLIA_APIKEY: ${{ secrets.ALGOLIA_APIKEY }}
        MASA_ALGOLIA_APPID: "TSB4MACWRC"
        MASA_ALGOLIA_INDEXPREFIX: "blazor-masastack-prd_"
        MASA_ROOT_DOCS_PATH: "/home/runner/work/MASA.Blazor/MASA.Blazor/docs/"
      run: dotnet run --project docs/Masa.Docs.Indexing/Masa.Docs.Indexing.csproj -c Release
