name: create doc index dev
# Create dev doc index,send to ALGOLIA
# auto create when doc changed
on:
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - docs/MASA.Docs/src/Masa.Framework.Docs/wwwroot/pages/**/zh-CN.md
  #    - docs/MASA.Docs/src/Masa.Framework.Docs/wwwroot/pages/**/en-US.md
  #    - docs/MASA.Docs/src/Masa.Stack.Docs/wwwroot/pages/**/zh-CN.md
  #    - docs/MASA.Docs/src/Masa.Stack.Docs/wwwroot/pages/**/en-US.md
  #    - docs/Masa.Blazor.Docs/wwwroot/pages/**/en-US.md
  #    - docs/Masa.Blazor.Docs/wwwroot/pages/**/zh-CN.md
  workflow_dispatch:

jobs:
  create-doc-index-dev:
    runs-on: ubuntu-latest
    steps:
    - name: git pull
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - run: git submodule foreach git checkout main
    - name: setting dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          7.0.x
    - name: run index-create tools
      env:
        MASA_DOC_DOMAIN: "https://blazor-dev.masastack.com/"
        MASA_ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        MASA_ALGOLIA_APP_ID: "TSB4MACWRC"
        MASA_ALGOLIA_INDEXP_REFIX: "blazor-masastack_dev_"
        MASA_ROOT_DOCS_PATH: "/home/runner/work/MASA.Blazor/MASA.Blazor/docs/"
        # MASA_DOC_EXCLUDE_URLS  if many please seperate with || ,ex: "/blazor/about/about||/blazor/about/meet-the-team"
        MASA_DOC_EXCLUDE_URLS: "/blazor/about/about||/blazor/about/meet-the-team"
      run: cd docs/Masa.Docs.Indexing && dotnet run --project Masa.Docs.Indexing.csproj --no-launch-profile -c Release
