name: create doc index prd
# Create dev doc index,send to ALGOLIA
# auto create when doc changed
on:
  workflow_dispatch:

jobs:
  create-doc-index-prd:
    runs-on: ubuntu-latest
    steps:
    - name: git pull
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - run: git submodule foreach git checkout main
    - name: setting dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          7.0.x
    - name: run index-create tools
      env:
        MASA_DOC_DOMAIN: "/"
        MASA_ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        MASA_ALGOLIA_APP_ID: "TSB4MACWRC"
        MASA_ALGOLIA_INDEXP_REFIX: "blazor-masastack_prd_"
        MASA_ROOT_DOCS_PATH: "/home/runner/work/MASA.Blazor/MASA.Blazor/docs/"
        # MASA_DOC_EXCLUDE_URLS  if many please seperate with || , e.g. "/blazor/about/about||/blazor/about/meet-the-team"
        MASA_DOC_EXCLUDE_URLS: "/blazor/about/about||/blazor/about/meet-the-team"
      run: cd docs/Masa.Docs.Indexing && dotnet run --project Masa.Docs.Indexing.csproj --no-launch-profile -c Release
