name: deploy-wasm-try

on:
  push:
    branches:
      - main
    paths:
      - src/Masa.Try.Shared/**
      - src/Masa.Try.WebAssembly/**
  workflow_dispatch:

jobs:
  deploy-try:
    runs-on: ubuntu-latest
    steps:
    - name: git pull
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - run: git submodule foreach git checkout main
    - name: setting dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
        include-prerelease: true
    - name: setting tools
      run: dotnet workload install wasm-tools-net7
    - name: build
      run: dotnet build Masa.Try.sln
    - name: publish
      run: dotnet publish src/Masa.Try.WebAssembly/Masa.Try.WebAssembly.csproj -c Release
    - name: setup oss
      uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-cn-hangzhou.aliyuncs.com"
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
    - name: deploy oss
      run: ossutil cp -rf /home/runner/work/MASA.Blazor/MASA.Blazor/src/Masa.Try.WebAssembly/bin/Release/net7.0/publish/wwwroot/ oss://masa-try/
