name: deploy-wasm-dev

on:
  push:
    branches:
      - main
    paths:
      - src/BlazorComponent/src/Component/**
      - src/Masa.Blazor/**
      - docs/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: git pull
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - run: git submodule foreach git checkout main
    - name: setting dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          7.0.x
        include-prerelease: true
    - name: setting tools
      run: dotnet workload install wasm-tools
    - name: build
      run: dotnet build Masa.Blazor.Docs.sln
    - name: publish
      run: dotnet publish docs/Masa.Docs.WebAssembly/Masa.Docs.WebAssembly.csproj -c Release
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed
    # - name: install python packages
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r scirpts/requirements.txt
    - name: execute py script # run sitemapgenerate.py
      env:
        DOC_DOMAIN: "https://blazor.masastack.com"
      run: python scirpts/sitemapgenerate.py
    - name: setup oss
      uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-cn-hangzhou.aliyuncs.com"
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
    - name: deploy oss
      run: ossutil cp -rf /home/runner/work/MASA.Blazor/MASA.Blazor/docs/Masa.Docs.WebAssembly/bin/Release/net7.0/publish/wwwroot/ oss://masa-blazor-wasm-dev/


